### ISSUE TITLE
zkvm: remove bulletproofs dependency from API

### ISSUE THREAD

**Issue by oleganza** [stellar/slingshot#210]
Would be good if BulletproofsGens and other entities from BP were encapsulated inside ZkVM or at least re-exported, so that the users can add ZkVM as a dependency w/o also bringing in bulletproofs. See `token` crate as an example.

1. `BulletproofsGens`: those can be instantiated by ZkVM with a capacity parameter. R1CS can take them at the `Prover::prove` method, so ZkVM can just create a necessary capacity based on number of multiplicative constraints used. This can also be a part of the `Tx` object.
2. `PedersenGens` are already baked into Commitment and Predicate API, and we can do the same for Signature/VerificationKey API, so users do not create those things with raw scalar operations. If they need to do something custom and unsupported by ZkVM APIs, then they can import Ristretto or Bulletproofs explicitly.
3. R1CS instance is already encapsulated inside ZkVM prover/verifier.

**Comment by vickiniu** [comment]
progress underway: https://github.com/dalek-cryptography/bulletproofs/pull/266

**Comment by oleganza** [comment]
Done in #405
