### ISSUE TITLE
zkvm: question: how to compress commitments?

### ISSUE THREAD

**Issue by SoraSuegami** [stellar/slingshot#251]
Thank you very much for sincerely answering my question in the before issue.
I am writing a program with zkvm.
https://github.com/Vreath-core/rust-vreath-core/tree/master/src/zk
I'd like to ask you how to compress commitments.

I first thought that Or predicate is compressed data of some predicates, so verifiers can get all program predicates that pushes commitments by decompressing Or predicate.
I found, however, Or predicate is just the array of predicates.

Is there any way to compress commitments? (Prover only has to share one commitments.)
For example, when three secret inputs x,y,z and one public input h is used, prover want to prove the following constraints by sharing  h or compressed commitment (not commitments of x,y,z).
y = x+1;
z = x * y:
h = hash(x,y,z);

I would appreciate it if you could tell me how to compress commitments.

**Comment by vickiniu** [comment]
Hey! I'm not entirely sure if this answers your question, but for Predicates, we have two representations: `Opaque` and `Witness`. The Witness form is (as you mentioned) an array of Predicates. 

However, the `Opaque` form is the blinded and compressed data that is sent over to the verifier. For the predicate disjunction in particular, you can see how that is constructed here: https://github.com/interstellar/slingshot/blob/main/zkvm/src/predicate.rs#L140

A slight caveat to all of this is that the Predicate tree representation in particular will be changing quite a bit as we move to a taproot-inspired implementation (see #248 for more details!)

Hope that helps :)

**Comment by SoraSuegami** [comment]
Thank you very much for answering my question many times!
I understood Opaque form can compress some predicates into constant size.

I think verifier need all commitments, because verifying proof requires not only the proof but also the byte array of the program that contains pushed commitments. 

I’d like to know how to verify proof with Opaque predicate.

**Comment by oleganza** [comment]
>I’d like to know how to verify proof with Opaque predicate.

See the `CallProof` and `call` instruction. The transaction proves that the opaque predicate is a commitment to a certain program, and VM then executes the program. Transaction obviously provides the program in the clear, together with the merkle path to it. 

https://github.com/stellar/slingshot/blob/main/zkvm/src/predicate.rs#L139
