### ISSUE TITLE
Schnorr Crate

### ISSUE THREAD

**Issue by goldenMetteyya** [stellar/slingshot#299]
Hello!

Amazing work being done here:) 

I have updated an old crate I had called Schnorr with your key tree and musig updates. Musig is not finished yet because I am trying to get the interface usable with sorted keys being handled internally. Also to make it easier for the crates users to integrate into a network protocol. Also adapter signature methods need to be added. 

https://github.com/stichtingorganism/schnorr

Would you be interested in consolidating efforts and making a robust create for the ecosystem?

best

**Comment by oleganza** [comment]
Cool, thanks for sharing.

Your use of `Transcript::proto_name` reminded me that we need to add `"dom-sep", "Musig.plain"` or something for single-message API.

**Comment by oleganza** [comment]
Factoring out schnorr sigs from our musig implementation is tracked here: #239.
