### ISSUE TITLE
zkvm:: no easy way to handle expr left by `range` instruction

### ISSUE THREAD

**Issue by SanJue** [stellar/slingshot#406]
for example:
I want to express: maxtime() > exp_time, 
for now, codes as following should be provided:

```
    let exp_time = 1_613_750_400_000u64; //2021-02-20T00:00:00
    let prog = Program::build(|p| {
        p.push(Commitment::blinded(exp_time))
            .var()
            .expr()
            .neg()
            .maxtime()
            .add()
            .range() // leave expr on stack, and only can be handled by eq
            .push(Commitment::blinded(exp_time))
            .var()
            .expr()
            .neg()
            .maxtime()
            .add()
            .eq()
            .verify();
    });
```

however, the following codes  are expected :

```
    let exp_time = 1_613_750_400_000u64; //2021-02-20T00:00:00
    let prog = Program::build(|p| {
        p.push(Commitment::blinded(exp_time))
            .var()
            .expr()
            .neg()
            .maxtime()
            .add()
            .range();
    });
```

so, should we change the design of `range` instruction?

0x0f | range | expr → expr | Modifies CS
-- | -- | -- | --

--->

0x0f | range | expr → ø | Modifies CS
-- | -- | -- | --

**Comment by oleganza** [comment]
Thanks for filing this example. My initial reaction was "if you don't need the expression, simply drop it". But then we can only drop copyable types. And expressions are not copyable to avoid DoS issues with cheaply expanded expressions.

Dropping expression by `range` is not very nice - you cannot copy it if you need to use it in further calculations. I suggest reviewing whether we can extend drop to more types, beyond copyable. E.g. programs, expressions and constraints should be safe to drop.

**Comment by oleganza** [comment]
@SanJue let me know what you think: https://github.com/stellar/slingshot/pull/407
