### ISSUE TITLE
blockchain: design and implement blockchain state machine protocol

### ISSUE THREAD

**Issue by oleganza** [stellar/slingshot#93]
ZkVM is stateless: its output is a [transaction log](https://github.com/interstellar/slingshot/blob/main/zkvm/spec/ZkVM.md#transaction-log) that contains instructions for an upstream protocol to delete and insert pieces of data (utxos and nonces). That protocol is a **blockchain state machine**: it takes in blocks of transactions, creates a ZkVM instance for each transaction, verifies them and applies changes to the state. Invalid transactions are rejected.

We want to implement this protocol with an abstract interface, w/o specifying exactly the serialization for blocks, or the consensus protocol. If we take out these parts from the [TxVM blockchain specification](https://github.com/chain/txvm/blob/main/specifications/blockchain.md) and adjust the merkle tree / patricia tree definitions to the Transcript-based versions, we'd get exactly what we need for ZkVM blockchain: rules for updating a set of utxos, nonces and checking time bounds.

We need:

* Rules for committing to the tx list, utxo set and nonce set per block
* Rules to validate individual transaction
* Rules to validate & apply a block of transactions
* Interface to storing/loading the state, so it can be implemented with in-memory storage or an arbitrary database.

**Comment by cathieyun** [comment]
Just to cross-link, @bobg is working on the spec here: https://github.com/interstellar/slingshot/pull/198

**Comment by oleganza** [comment]
Duplicate of #277
